config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations"
  }

  root to: "maps#index"
  resources :maps, only: [:index]
  resources :lessons, only: [:index]
  resource :contacts, only: [:new, :create]

  resources :abouts, except: [:index, :destroy] do
    resource :hangers, only: [:create, :destroy]
    collection do
      get "location"
    end
  end

  resources :pairs, except: [:show, :edit, :update] do
    resources :messages, only: [:index, :create]
  end

end

app/models/hanger.rb
# == Schema Information
#
# Table name: hangers
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  about_id   :integer
#  user_id    :integer
#
class Hanger < ApplicationRecord

  belongs_to :user
  belongs_to :about

end

app/controllers/hangers_controller.rb
class HangersController < ApplicationController

  before_action :set_hanger, only: [:create, :destroy]


  def create
    hanger = current_user.hangers.new(about_id: params[:about_id])
    hanger.save
  end

  def destroy
    # alternative idea
    # hanger = current_user.hangers.find_by(about_id: params[:about_id])
    hanger = Hanger.find_by(about_id: params[:about_id], user_id: current_user.id)
    hanger.destroy
  end


  private
  def set_hanger
    @about = About.new(id: params[:about_id])
  end

end

app/helpers/hangers_helper.rb
module HangersHelper
end

app/views/hangers/_hanger.html.haml
-# ===== from abouts#show ===========================
- if @about.already_hangered_on?(current_user)
  .hangerCode__hangerCodeIf
    %span.spanHangerRemove Already Hanger on the Door. Remove it now ?：
    = link_to about_hangers_path(@about.id), method: :delete, remote: true, class: "hangerLogoLink", data: { confirm: "remove this hanger ?" } do
      %i.fas.fa-weight-hanging.hangerRemove
- else
  .hangerCode__hangerCodeIf
    %span.spanHangerAdd Put Hanger on the Door ? :
    = link_to about_hangers_path(@about.id), method: :post, remote: true, class: "hangerLogoLink" do
      %i.fas.fa-weight-hanging.hangerAdd

app/views/hangers/create.js.haml
$("#hangers_buttons_#{@about.id}").html('#{escape_javascript(render partial: "hangers/hanger", locals: {about: @about})}');

app/views/hangers/destroy.js.haml
$("#hangers_buttons_#{@about.id}").html('#{escape_javascript(render partial: "hangers/hanger", locals: {about: @about})}');