config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations"
  }

  root to: "maps#index"
  resources :maps, only: [:index]
  resources :lessons, only: [:index]
  resource :contacts, only: [:new, :create]

  resources :abouts, except: [:index, :destroy] do
    resource :hangers, only: [:create, :destroy]
    collection do
      get "location"
    end
  end

  resources :pairs, except: [:show, :edit, :update] do
    resources :messages, only: [:index, :create]
  end

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :bigint           not null, primary key
#  content    :string(255)
#  image      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  pair_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_messages_on_pair_id  (pair_id)
#  index_messages_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (pair_id => pairs.id)
#  fk_rails_...  (user_id => users.id)
#
class Message < ApplicationRecord

  belongs_to :pair
  belongs_to :user
  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader

  has_many :notifications, dependent: :destroy

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :login_check_messages, only: [:index]
  before_action :set_message, only: [:index, :create]
  before_action :onlyTwoPersons_canUsePairDoor_check, only: [:index, :create]


  def index
    @aboutAZ = About.find_by(user_id: UsersPair.where(pair_id: params[:pair_id]).where.not(user_id: current_user.id)[0].user_id)
    @message = Message.new
    @messages = @pair.messages.includes(:user)
    # (kkd)messages#indexを開封 -> 未確認checked:falseの全てが確認済checked:true
    @notifications = current_user.passive_notifications
    @notifications.where(checked: false).each do |notification|
      # 対象ペアのkkdのみ処理
      if notification.pair_id == params[:pair_id].to_i
        notification.update_attributes(checked: true)
      end
    end
  end

  def create
    @message = @pair.messages.new(message_params)
    if @message.save
      # sendAMessage -> callMethod toCreteNewNotification
      @pair.create_notification_message(current_user, @message.id)
      redirect_to pair_messages_path(@pair)
    else
      @messages = @pair.messages.includes(:user)
      render :index
    end
  end


  private
  def login_check_messages
    redirect_to new_user_session_path unless user_signed_in?
  end

  def set_message
    @pair = Pair.find_by(id: params[:pair_id])
  end

  def message_params
    # mergeTwoHashes toRegisterUser_id forMessagesTable
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def onlyTwoPersons_canUsePairDoor_check
    pairIdArray = []
    currentUserPairsArray  = []
    pairIdArray << params[:pair_id].to_i
    current_user.users_pairs.each do |cur|
      currentUserPairsArray << cur.pair_id
    end
    redirect_to root_path if (pairIdArray & currentUserPairsArray).blank?
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.haml
-# ===== messages#index transfer part ================
.trans
  .trans__transContent
    .trans__transContent__transContentDoors
      .trans__transContent__transContentDoors__transContentDoorsLink
        = link_to "Open DoorS", pairs_path(current_user), class: "doorsLink"
    .trans__transContent__transContentState
      .trans__transContent__transContentState__transContentStateLink
        .trans__transContent__transContentState__transContentStateLink__transContentStateLinkBtn
          = link_to "About HIM / HER", about_path(@aboutAZ), class: "transBtn transBtnDoor"

-# ===== messages#index part =========================
.mess
  -# ---- top form ------------------------------
  .mess__messContent
    -# ````` Title ```````````````````````
    .mess__messContent__messContentTitle
      .mess__messContent__messContentTitle__messContentTitleDoor
        %h2.kkdDoor ~~ Knock-Knock Door ~~
      .mess__messContent__messContentTitle__messContentTitlePair
        %h6.kkdPairSomeone about HIM/HER
        %h6.kkdPairMe about ME
    -# ````` Pair Users ``````````````````
    .mess__messContent__messContentPair
      .mess__messContent__messContentPair__messContentPairYou
        .mess__messContent__messContentPair__messContentPairYou__messContentPairYouIcon
          - @pair.users.each do |user|
            - us = User.find_by(name: user.name)
            - if us.id != current_user.id
              - us.about.photos.each do |ph|
                = image_tag  ph.image.url, size: "55x55"
        .mess__messContent__messContentPair__messContentPairYou__messContentPairYouName
          - if @pair.users[0].name != current_user.name
            = @pair.users[0].name
          - else
            = @pair.users[1].name
      .mess__messContent__messContentPair__messContentPairMe
        .mess__messContent__messContentPair__messContentPairMe__messContentPairMeIcon
          - current_user.about.photos.each do |p|
            = image_tag p.image.url, size: "55x55"
        .mess__messContent__messContentPair__messContentPairMe__messContentPairMeName
          = current_user.name

  -# ---- Display Form --------------------------
  .mess__messPost
    .mess__messPost__messPostChat
      .mess__messPost__messPostChat__messPostChatBox
        .mess__messPost__messPostChat__messPostChatBox__messPostChatBoxRL
          - @pair.messages.each do |message|
            - if message.user_id == current_user.id
              .messRight
                .RLDate
                  = message.created_at.strftime("%Y/%m/%d(%a) %H:%M(%Z)")
                .RLMessage
                  - if message.content.present?
                    .RLMessageContent
                      = message.content
                  - if message.image.present?
                    .RLMessageImage
                      = image_tag message.image.url, class: "chatImage", size: "123x123"
            - else
              .messLeft
                .RLDate
                  = message.created_at.strftime("%Y/%m/%d(%a) %H:%M(%Z)")
                .RLMessage
                  - if message.content.present?
                    .RLMessageContent
                      = message.content
                  - if message.image.present?
                    .RLMessageImage
                      = image_tag message.image.url, class: "chatImage", size: "123x123"


  -# ---- Submit Form ---------------------------
  .mess__messSubmit
    .mess__messSubmit__messSubmitForm
      = form_with model: [@pair,@message], class: "messForm", local: true do |f|
        .messFormBoard
          = f.text_field :content, class: "messText", placeholder: " type from here"
          .messMask
            = f.label :image, class: "messLabel" do
              %i.fas.fa-camera-retro.chatIcon
              = f.file_field :image, class: "messFile"
        .messFormBtn
          = f.submit "SEND", class: "messSubmitBtn"