config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations"
  }

  root to: "maps#index"
  resources :maps, only: [:index]
  resources :lessons, only: [:index]
  resource :contacts, only: [:new, :create]

  resources :abouts, except: [:index, :destroy] do
    resource :hangers, only: [:create, :destroy]
    collection do
      get "location"
    end
  end

  resources :pairs, except: [:show, :edit, :update] do
    resources :messages, only: [:index, :create]
  end

end

app/models/pair.rb
# == Schema Information
#
# Table name: pairs
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Pair < ApplicationRecord

  has_many :users_pairs, dependent: :destroy
  has_many :users, through: :users_pairs
  accepts_nested_attributes_for :users_pairs, allow_destroy: true

  has_many :messages, dependent: :destroy
  accepts_nested_attributes_for :messages, allow_destroy: true

  has_many :notifications, dependent: :destroy


  # ----- notification -----------------------------
  def create_notification_message(current_user, message_id)
    # メッセージをした全ての人(自分以外)のuser_id取得 -> 重複なし -> 全員に通知
    temp_ids = Message.select(:user_id).where(pair_id: id).where.not(user_id: current_user.id).distinct
    # [1]自分宛てのメッセージが有り場合
    temp_ids.each do |temp_id|
      save_notification_message(current_user, message_id, temp_id["user_id"])
    end
    # [2]自分宛てのメッセージが無し（メッセージ送付した一発目の）場合
    save_notification_message(current_user, message_id, user_ids) if temp_ids.blank?
  end

  def save_notification_message(current_user, message_id, visited_id)
    # 同一ペアで複数回メッセージ有りの場合 -> そのペア向けに、複数回分の呼び出し内容をDBへ保存
    notification = current_user.active_notifications.new(
      pair_id: id,
      message_id: message_id,
      visited_id: UsersPair.where(pair_id: id).where.not(user_id: current_user.id)[0].user_id,
      action: "message"
    )
    # 自分からメッセージを送った場合 -> 通知済みtrue(新規通知なし)
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController

  before_action :login_check_pairs, only: [:index]
  before_action :already_pair_exist_check, only: [:new]
  before_action :create_currentUserAbout_before_pairStart_check, only: [:index, :new]
  before_action :set_pair, only: [:new, :create]


  def index
    @currentHangers = current_user.hangers
    @currentUsersPairs = current_user.users_pairs
    # current_userに紐づく、自分宛の通知passive_notifications
    @notifications = current_user.passive_notifications
  end

  def new
    @pair.users << current_user
    @about = About.find_by(id: params[:format])
  end

  def create
    if @pair.save
      @pair.users = User.where(id: params[:pair][:user_ids])
      redirect_to pair_messages_path(@pair)
    else
      render :new
    end
  end

  def destroy
    @pair = Pair.find_by(id: params[:id])
    @pair.destroy
    redirect_to pairs_path
  end


  private
  def login_check_pairs
    redirect_to new_user_session_path unless user_signed_in?
  end

  def create_currentUserAbout_before_pairStart_check
    currentUserAbout = About.where(user_id: current_user.id)
    if currentUserAbout.blank?
      redirect_to new_about_path
    end
  end

  def already_pair_exist_check
    @about = About.find_by(id: params[:format])
    currentArray = []
    ataboutArray = []
    UsersPair.where(user_id: current_user.id).each do |c|
      currentArray << c.pair_id
    end
    UsersPair.where(user_id: @about.user_id).each do |a|
      ataboutArray << a.pair_id
    end
    commonPairId = currentArray & ataboutArray
    unless commonPairId.empty?
      @pair = Pair.find_by(id: commonPairId)
      redirect_to pair_messages_path(@pair)
    end

    def set_pair
      @pair = Pair.new
    end
  end

end

app/helpers/pairs_helper.rb
module PairsHelper
end

app/views/pairs/_newSecondHeader.html.haml
-# ===== pairs#new second header part ===================
.trans
  .trans__transContent
    .trans__transContent__transContentDoors
      .trans__transContent__transContentDoors__transContentDoorsLink
        = link_to "Open DoorS", pairs_path, class: "doorsLink"
    .trans__transContent__transContentState
      .trans__transContent__transContentState__transContentStateLink
        .trans__transContent__transContentState__transContentStateLink__transContentStateLinkBtn
          = link_to "Back to About HIM / HER", about_path(@about.id), class: "transBtn transBtnDoor"

app/views/pairs/index.html.haml
-# ==== pairs#index part ================================
.pairIndex
  .pairIndex__pairIndexContent
    -# ---- DoorS title ---------------------------
    .pairIndex__pairIndexContent__pairIndexContentTitle
      .pairIndex__pairIndexContent__pairIndexContentTitle__pairIndexContentTitleHead
        %h2.pairIndexTitleHead DoorS
      .pairIndex__pairIndexContent__pairIndexContentTitle__pairIndexContentTitleCode


    -# ---- door hanger list-----------------------
    .pairIndex__pairIndexContent__pairIndexContentHanger
      .pairIndex__pairIndexContent__pairIndexContentHanger__pairIndexContentHangerHead
        %i.fas.fa-weight-hanging.pairIndexDoorLogo
        %h3.pairIndexHangerHead door hangers

      .pairIndex__pairIndexContent__pairIndexContentHanger__pairIndexContentHangerCode
        .pairIndex__pairIndexContent__pairIndexContentHanger__pairIndexContentHangerCode__pairIndexContentHangerCodeLimit
          .table-responsive
            %table.table.table-hover.table-bordered
              %caption List of hangers
              %thead.thead-light
                %tr.h3
                  %th{scope: "col"} Date
                  %th{scope: "col"} Icon
                  %th{scope: "col"} Name
                  %th{scope: "col"} HIM/HER
                  %th{scope: "col"} Door
              %tbody
                - @currentHangers.each do |currentHanger|
                  - currentUser_usersPair_Array = []
                  - currentUser_usersPairs = UsersPair.where(user_id: current_user.id)
                  - currentUser_usersPairs.each do |currentUser_usersPair|
                    - currentUser_usersPair_Array << currentUser_usersPair.pair_id
                  - hangerAbout = About.find_by(id: currentHanger.about_id)
                  - hangerAbout_usersPair_Array = []
                  - hangerAbout_usersPairs = UsersPair.where(user_id: hangerAbout.user_id)
                  - hangerAbout_usersPairs.each do |hangerAbout_usersPair|
                    - hangerAbout_usersPair_Array << hangerAbout_usersPair.pair_id
                  - if (currentUser_usersPair_Array & hangerAbout_usersPair_Array).blank?
                    %tr.h5.tableRecord
                      %td
                        = currentHanger.updated_at.strftime("%Y/%m/%d")
                      %td
                        - hangerPhoto = Photo.find_by(about_id: currentHanger.about_id)
                        - if hangerPhoto.blank?
                          = p "no icon"
                        - else
                          = image_tag hangerPhoto.image.url, class: "pairsIndexHangerPhoto", size: "44x44"
                      %td
                        -# - hangerAbout = About.find_by(id: currentHanger.about_id)
                        - hangerUser = User.where(id: hangerAbout.user_id)
                        = hangerUser[0].name
                      %td
                        = link_to "About", about_path(hangerAbout), class: "pairsIndexAboutHanger"
                      %td
                        = link_to "knock-knock", new_pair_path(hangerAbout), class: "pairsIndexKnockHanger"


    -# ---- knocked door list ---------------------
    .pairIndex__pairIndexContent__pairIndexContentDoor
      .pairIndex__pairIndexContent__pairIndexContentDoor__pairIndexContentDoorHead
        %i.fas.fa-door-open.pairIndexHangerLogo
        %h3.pairIndexDoorHead knocked doors

      .pairIndex__pairIndexContent__pairIndexContentDoor__pairIndexContentDoorNotification
        .pairIndex__pairIndexContent__pairIndexContentDoor__pairIndexContentDoorNotification__pairIndexContentDoorNotificationBody
          - if @notifications.exists?
            -# ````` @notificstionsが存在する ``````````
            - if unchecked_notifications.any?
              -# 未確認メッセージ有り
              %i.far.fa-bell.beNotifNoCheck
                New message in Knock-Knock Door.
            - else
              -# 未確認メッセージ無し
              %i.far.fa-bell.beNotifChecked
                Checked messages in Knock-Knock Door.
          - else
            -# ````` @notificstionsが存在しない ````````
            %i.far.fa-bell.noNotif
              No message yet. Why don't you send a message?

      .pairIndex__pairIndexContent__pairIndexContentDoor__pairIndexContentDoorCode
        .pairIndex__pairIndexContent__pairIndexContentDoor__pairIndexContentDoorCode__pairIndexContentDoorCodeLimit
          .table-responsive
            %table.table.table-hover.table-bordered
              %caption List of knock-knocks
              %thead.thead-light
                %tr.h3
                  %th{scope: "col"} Date
                  %th{scope: "col"} Icon
                  %th{scope: "col"} Name
                  %th{scope: "col"} HIM/HER
                  %th{scope: "col"} Door
                  %th{scope: "col"} Last Message
                  %th{scope: "col"} Delete Door
              %tbody
                - @currentUsersPairs.each do |currentUsersPair|
                  - upwwn = UsersPair.where(pair_id: currentUsersPair.pair_id).where.not(user_id: current_user.id)[0]
                  - aboutUpwwn = About.find_by(user_id: upwwn.user_id)
                  %tr.h5
                    %td
                      - messages = Message.where(pair_id: currentUsersPair.pair_id)
                      - lastMessage = messages.last
                      - if lastMessage.blank?
                        = currentUsersPair.updated_at.strftime("%Y/%m/%d")
                      - else
                        = lastMessage.created_at.strftime("%Y/%m/%d")
                    %td
                      - photoAboutUpwwn = Photo.where(about_id: aboutUpwwn.id)
                      - if photoAboutUpwwn.blank?
                        = p "no icon"
                      - else
                        = image_tag photoAboutUpwwn[0].image.url, class: "pairsIndexPhotoAboutUpwwn", size: "44x44"
                    %td
                      - userUpwwn = User.find_by(id: upwwn.user_id)
                      = userUpwwn.name
                    %td
                      = link_to "About", about_path(aboutUpwwn), class: "pairsIndexAboutPair"
                    %td
                      = link_to "knock-knock", pair_messages_path(currentUsersPair.pair_id), class: "pairsIndexKnockPair"
                    %td
                      - messages = Message.where(pair_id: currentUsersPair.pair_id)
                      - lastMessage = messages.last
                      - if lastMessage.blank?
                        = "no message yet."
                      - else
                        - if lastMessage.image.present? && lastMessage.content.blank?
                          = "last one is the picture."
                        - else
                          = lastMessage.content
                    %td
                      = link_to "delete", pair_path(currentUsersPair.pair_id), class: "pairsIndexDoorDelete", method: :delete, data: {confirm: "delete this door really ? :_("}

app/views/pairs/new.html.haml
-# ===== pairs#new second header part ===================
= render "newSecondHeader"


-# ===== pairs#new part  ================================
.pairNew
  .pairNew__pairNewContent

    .pairNew__pairNewContent__pairNewContentTitle
      %h1.kkdAsk
        knock on the door ??

    .pairNew__pairNewContent__pairNewContentName
      .pairNew__pairNewContent__pairNewContentName__pairNewContentNameMe
        %h3.pairNewMeText
          《 My name 》
        .pairNewMePerson
          = current_user.name
      .pairNew__pairNewContent__pairNewContentName__pairNewContentNameYou
        %h3.pairNewYouText
          《 Him/Her name 》
        .pairNewYouPerson
          = @about.user.name

    .pairNew__pairNewContent__pairNewContentDo
      %h4.kkdText
        > check both "knobs" below , and Knock-Knock Door !

    .pairNew__pairNewContent__pairNewContent
      .pairNew__pairNewContent__pairNewContent__pairNewContentCheck
        = form_with model: [@pair] do |f|
          .kkdCollectionCheck
            = f.collection_check_boxes :user_ids, User.where(id: current_user.id).or(User.where(id: @about.user_id)), :id, :name
          .kkdCollectionSubmit
            = f.submit "Knock-Knock Door !", class: "kkdCollectionSubmitBtn"