config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations"
  }

  root to: "maps#index"
  resources :maps, only: [:index]
  resources :lessons, only: [:index]
  resource :contacts, only: [:new, :create]

  resources :abouts, except: [:index, :destroy] do
    resource :hangers, only: [:create, :destroy]
    collection do
      get "location"
    end
  end

  resources :pairs, except: [:show, :edit, :update] do
    resources :messages, only: [:index, :create]
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  require "open-uri"
  require "nokogiri"
  require "news-api"
  require "date"


  def index
    # ===== Marker Position ============================
    gon.nameArray = []
    gon.aboutIdArray = []
    gon.latArray = []
    gon.lngArray = []
    gon.invArray = []

    # ----- pick noneAboutUser to skip -----------
    userIdArray = []
    noneAboutUserIdArray = []
    User.all.each do |user|
      userIdArray << user.id
    end
    userIdArray.each do |userId|
      if About.where(user_id: userId).blank?
        noneAboutUserIdArray << userId
      end
    end

    # ----- send allUserGon [user.id order] ------
    User.all.each do |user|
      noneAboutUserIdArray.each do |noneAboutUserId|
        if user.id == noneAboutUserId
          # ````` skip noneAboutUserName `````
        else
          gon.nameArray << user.name
        end
      end
    end
    About.all.order(user_id: "ASC").each do |about|
      gon.aboutIdArray << about.id
      gon.latArray << about.latitude
      gon.lngArray << about.longitude
      gon.invArray << about.invitation
    end


    # ===== Center Coordinate   ========================
    if user_signed_in? && About.find_by(user_id: current_user.id).present?
      @signInCurrentUserAbout = About.find_by(user_id: current_user.id)
      gon.currentUserName = current_user.name
      gon.currentUserAboutId = @signInCurrentUserAbout.id
      gon.currentUserLat = @signInCurrentUserAbout.latitude
      gon.currentUserLng = @signInCurrentUserAbout.longitude
      gon.currentUserInv = @signInCurrentUserAbout.invitation
    end


    # ===== News =======================================
    newsApi = News.new(ENV['NEWS_API_KEY'])
    @scoops = newsApi.get_everything(q:"travel", from:"Date.today.days_ago(27)", to:"Date.today.days_ago(1)", pageSize:"3", language:"en", sortBy: "publishedAt")
  end

end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_footer.html.haml
-# ===== from layouts/application.html.haml =================
.footer
  .footer__footerContent
    .footer__footerContent__footerContentFoot
      .foot
        %ul.footUl
          %li.footUlLi
            %h2.footUlLiHead
              "About Us"
            %ul.footUlLiBody
              %li= link_to "Adventure", lessons_path, class: "footest"
              %li#jsModalOpen
                = link_to "Our Team", root_path , class: "footest"
              .modal.jsModal
                .modal__modalBackground#jsModalClose
                .modal__modalContent
                  %p
                    Message from our team
                    %br
                    %br
                    %br
                    We believe we can make world a better place by travel, and enrich travel by connection.
                    %br
                    Knock-Knock is about sharing our lives and feelings with others, to understand their culture and to foster mutual respect.
                    %br
                    Knock-Knock will make communication with locals and travellers easier in every country on Earth.
                    %br
                    Travel like a local, find your new home and experience the world in a way money cannot buy.
                    %br
                    There is a community of knock-knockers near you.
                    %br
                    Dance, sing, act! Hike and eat out!
                    %br
                    Make the world a little smaller, a little friendlier.
                    %br
                    Open your mind and heart to others.
                    %br
                    You will be awarded with unforgettable experiences.
                    %br
                    %br
                    %br
                    Knock-Knock began in 2020 as a small passion project by founders R.O. & Ben.
                    %br
                    While we were traveling, we could not find infomation we wanted online.
                    %br
                    So we decided to provide an online platform for travelers to exchange infomation simply.
                    %br
                    From now on we are here to support your travel experience.
                    %br
                    And we hope you will find this web site usuful.
                    %br
                    We are waiting for your click on the "contact" button at footer on application's top view.
                    %br
                    We will keep improving this web site for you.
                    %br
                    Enjoy your travel! Good luck!
                    %br
                    %br
                    %br
                    Sincerely R.O. & Ben
                    %br
              %li= link_to "Contacts", new_contacts_path, class: "footest"
          %li.footUlLi
            %h2.footUlLiHead
              "Support"
            %ul.footUlLiBody
              %li= link_to "Currency", root_path, class: "footest", data: {confirm: "Under maintenance."}
              %li= link_to "Insights", root_path, class: "footest", data: {confirm: "Under maintenance."}
              %li= link_to "Guides", root_path, class: "footest", data: {confirm: "Under maintenance."}
          %li.footUlLi
            %h2.footUlLiHead
              "Related Sites"
            %ul.footUlLiBody
              %li= link_to "Booking.com", "https://www.booking.com/index.en-gb.html", class: "footest"
              %li= link_to "Skyscanner", "https://www.skyscanner.net/", class: "footest"
              %li= link_to "Tripadvisor", "https://www.tripadvisor.com/", class: "footest"

    .footer__footerContent__footerContentRights
      .rahoo
        %h1.rahooHead
          Copyright (C) 2020 Rahoo! Corporation. All Rights Reserved.

app/views/maps/_header.html.haml
-# ===== from layouts/application.html.haml =================
.header
  .header__headerContent
    .header__headerContent__headerContentDoor
      .header__headerContent__headerContentDoor__headerContentDoorLogo
        = link_to root_path, class: "doorOpen" do
          %i.fas.fa-hiking
          %i.fas.fa-door-open
          -# operatingSound
          -# %audio{controls: "", autoplay: "", class: "audioKnock", src: "https://res.cloudinary.com/code-kitchen/video/upload/v1555038697/posts/zk5sldkxuebny7mwlhh3.mp3"}
    .header__headerContent__headerContentKnock
      .header__headerContent__headerContentKnock__headerContentKnockTitle
        = link_to "Knock-Knock!", root_path, class: "knockknock"
    .header__headerContent__headerContentLink
      - if user_signed_in?
        .header__headerContent__headerContentLink__headerContentLinkLeft
          - if About.find_by(user_id: current_user.id).present?
            = link_to "AboutMe", about_path(About.find_by(user_id: current_user.id).id), class: "leftBtn"
          - else
            = link_to "AboutMe", new_about_path, class: "leftBtn"
        .header__headerContent__headerContentLink__headerContentLinkRight
          = link_to "LogOut", destroy_user_session_path, class: "rightBtn", method: :delete, data: {confirm: "log out really ? :("}
      - else
        .header__headerContent__headerContentLink__headerContentLinkLeft
          = link_to "SignUp", new_user_registration_path, class: "leftBtn"
        .header__headerContent__headerContentLink__headerContentLinkRight
          = link_to "LogIn", new_user_session_path, class: "rightBtn"

.displayPop
  - unless user_signed_in?
    .displayPop__displayPopNo
      %h5.displayPopNoName
        visiter
  - else
    .displayPop__displayPopCurrent
      %h5.displayPopCurrentTitle
        current;
        %br
      %h5.displayPopCurrentName
        = current_user.name
      %h5.displayPopCurrentSpot
        - if About.find_by(user_id: current_user.id).present?
          - @currentUserAbout = About.find_by(user_id: current_user.id)
          = @currentUserAbout.nowCountry if @currentUserAbout.nowCountry.present?
          = " , " if @currentUserAbout.nowCountry.present? && @currentUserAbout.nowCity.present?
          = @currentUserAbout.nowCity if @currentUserAbout.nowCity.present?

app/views/maps/index.html.haml
.wrapper
  .banner
    .banner__bannerContent
      .banner__bannerContent__bannerContentImage
        %p#slideshow.slideshow
          -# considering alternative syntax
          -# %img.active{alt: "noReadable", src: "freeTravelPhoto1.jpg", width: "543px", height: "345px"}
          -# = image_tag "/assets/freeTravelPhoto1.jpg", alt: "noReadable", class: "active "
          -# = image_tag "freeTravelPhoto1.jpg", alt: "noReadable", class: "active "
          -# -------------------
          = image_tag asset_path("freeTravelPhoto1.jpg"), alt: "noReadable", class: "active "
          = image_tag asset_path("freeTravelPhoto2.jpg"), alt: "noReadable"
          = image_tag asset_path("freeTravelPhoto3.jpg"), alt: "noReadable"
          = image_tag asset_path("freeTravelPhoto4.jpg"), alt: "noReadable"
          = image_tag asset_path("freeTravelPhoto5.jpg"), alt: "noReadable"
          = image_tag asset_path("freeTravelPhoto6.jpg"), alt: "noReadable"
          = image_tag asset_path("freeTravelPhoto7.jpg"), alt: "noReadable"
          = image_tag asset_path("freeTravelPhoto8.jpg"), alt: "noReadable"
          = image_tag asset_path("freeTravelPhoto9.jpg"), alt: "noReadable"
          = image_tag asset_path("freeTravelPhoto10.jpg"), alt: "noReadable"
          = image_tag asset_path("freeTravelPhoto11.jpg"), alt: "noReadable"

  .mapper
    .mapper__mapperContent
      .mapper__mapperContent__mapperContentHead
        .mapper__mapperContent__mapperContentHead__mapperContentHeadLetter
          %h1.letter.letter1 " Life is a journey, journey is a life. "
          %h2.letter.letter2 〜 人生とは旅であり、旅とは人生である 〜
          %h3.letter.letter3 by Hidetoshi Nakata
      .mapper__mapperContent__mapperContentBody
        .mapper__mapperContent__mapperContentBody__mapperContentBodyAtlas
          .mapper__mapperContent__mapperContentBody__mapperContentBodyAtlas__mapperContentBodyAtlasWord
            Find Travellers and Try to Talk
          .mapper__mapperContent__mapperContentBody__mapperContentBodyAtlas__mapperContentBodyAtlasGo
            #map

  .teller
    .teller__tellerContent
      .teller__tellerContent__tellerContentSuggestion
        .teller__tellerContent__tellerContentSuggestion__tellerContentSuggestionBody
          -# suggestion items later
      .teller__tellerContent__tellerContentNews
        .teller__tellerContent__tellerContentNews__tellerContentNewsBody
          .teller__tellerContent__tellerContentNews__tellerContentNewsBody__tellerContentNewsBodyTitle
            %h2.newsTitle News
          .teller__tellerContent__tellerContentNews__tellerContentNewsBody__tellerContentNewsBodyCode
            .newsCode
              - @scoops.each do |scoop|
                .newsCode__newsCodeUrlImage
                  = link_to scoop.url, class: "scoopUrl" do
                    - if scoop.urlToImage.present?
                      = image_tag scoop.urlToImage, class: "scoopUrlToImage", width: "169", height: "121"
                .newsCode__newsCodeDateTitleDescription
                  .newsCode__newsCodeDateTitleDescription__newsCodeDateTitleDescription--date
                    = DateTime.iso8601(scoop.publishedAt, Date::ENGLAND).to_date.to_s
                  .newsCode__newsCodeDateTitleDescription__newsCodeDateTitleDescription--title
                    = scoop.title
                  .newsCode__newsCodeDateTitleDescription__newsCodeDateTitleDescription--description
                    = scoop.description